### ISSUE TITLE
关于模型的选择

### ISSUE THREAD

**Issue by Yumo216** [jarviszhb/KnowledgeTracing#2]
直接运行会提示
Usage:
    run.py (rnn|sakt) --hidden=<h> [options]
请问怎么选择模型呢

**Comment by jarviszhb** [comment]
好久没运行过了，刚刚测试了一下，在所有的包都安装好了的前提下，在根目录下新建一个log文件夹，然后在根目录下运行命令
`python -m evaluation.run rnn --hidden=8`，就可以了，rnn换成sakt就可以运行sakt模型，--hidden是必填项，用来控制模型的hidden state维度

**Comment by jarviszhb** [comment]
> 直接运行会提示
> Usage:
> run.py (rnn|sakt) --hidden= [options]
> 请问怎么选择模型呢

好久没运行过了，刚刚测试了一下，在所有的包都安装好了的前提下，在根目录下新建一个log文件夹，然后在根目录下运行命令
python -m evaluation.run rnn --hidden=8，就可以了，rnn换成sakt就可以运行sakt模型，--hidden是必填项，用来控制模型的hidden state维度

**Comment by Yumo216** [comment]
> 
> 
> > 直接运行会提示
> > Usage:
> > run.py (rnn|sakt) --hidden= [options]
> > 请问怎么选择模型呢
> 
> 好久没运行过了，刚刚测试了一下，在所有的包都安装好了的前提下，在根目录下新建一个log文件夹，然后在根目录下运行命令
> python -m evaluation.run rnn --hidden=8，就可以了，rnn换成sakt就可以运行sakt模型，--hidden是必填项，用来控制模型的hidden state维度

成功了，感谢，另外请问为啥不可以在直接在run.py里右键运行啊，还有可以加您一个联系方式吗，我qq，wx同号1005270531
